// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: bank.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getBankByID = `-- name: GetBankByID :one
SELECT bank_uuid, code, name, country_code 
  FROM bank
 WHERE bank_uuid =$1
`

func (q *Queries) GetBankByID(ctx context.Context, bankUuid uuid.UUID) (Bank, error) {
	row := q.db.QueryRowContext(ctx, getBankByID, bankUuid)
	var i Bank
	err := row.Scan(
		&i.BankUuid,
		&i.Code,
		&i.Name,
		&i.CountryCode,
	)
	return i, err
}
