// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	FindAccountStatuses(ctx context.Context) (FindAccountStatusesRow, error)
	FindLastActivityByAccount(ctx context.Context, accountUuid uuid.UUID) (AccountActivity, error)
	GetAccountByID(ctx context.Context, accountUuid uuid.UUID) (Account, error)
	GetBankByID(ctx context.Context, bankUuid uuid.UUID) (Bank, error)
	GetConfigurationByBankID(ctx context.Context, bankUuid uuid.UUID) (Configuration, error)
	GetConfigurationByID(ctx context.Context, configurationUuid uuid.UUID) (Configuration, error)
}

var _ Querier = (*Queries)(nil)
